export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const DELETE_FLASH_ALL_MESSAGE = 'DELETE_FLASH_ALL_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_EXPLORER = 'SET_EXPLORER';
export const SET_PERFORMANCE = 'SET_PERFORMANCE';